server:
  port: 8000

zuul:
  prefix: /api
  routes:
    multiplications:
      path: /multiplications/**
      url: http://localhost:1993/multiplications
    results:
      path: /results/**
      url: http://localhost:1993/results
    leaders:
      path: /leaders/**
      url: http://localhost:1992/leaders
    stats:
      path: /stats/**
      url: http://localhost:1992/stats

endpoints:
  trace:
    sensitive: false

ribbon:
  eureka:
    enabled: false
